### PR TITLE
We struggled to get a windows .exe to build from the uavcan 'develop' branch....

### PR DESCRIPTION
**Pull request by davidbuzz**
You'll need to edit 'paths' in make_exe3.bat , uavcan_gui_tool.spec.good and UAVCAN GUI Tool2.nsi to match the full-path/s that you are using, but this worked for me.  
I now have a windows .exe that works with WPython64-3760 and is built with 'pyinstaller' and the .spec file and then assembled into an 'installer' with NSIS 3.05 from https://nsis.sourceforge.io/Download and the .nsi file

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Thanks, David. Please tell us why exactly did you decide to add another build recipe alongside already existing one?

**Comment by davidbuzz** [comment]
Existing cx_freeze solution did not work for us, at all.

**Comment by pavel-kirienko** [comment]
Closing due to unresponsiveness.

**Comment by davidbuzz** [comment]
I reconmend u simply use a clean windows box to try to buid a .exe for yourself and when u are fully informed about how it fails utterly and completely, remember to come back here and reconsider this, which worked for me.

**Pull request closed without merging**
