### PR TITLE
Custom dsdl loader

### PR DESCRIPTION
**Pull request by SyrianSpock**
This PR implements an additional window that pops after CAN interface selection to allow users to load custom dsdl definitions. This solves #11.

The dsdl directory is set to the current directory by default. 
The first way of setting it is using the text box with the help of autocomplete:

The second way is by browsing the file system:

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Thank you, this is valuable and long needed for (https://github.com/UAVCAN/gui_tool/issues/11). However, I don't think it is a good UX practice to run the user through a quiz whenever the application is started. This is one of the reasons why the interface configuration window is bound to be removed in a future revision of the application (https://github.com/UAVCAN/gui_tool/issues/13).

For now I propose to integrate the DSDL loading capability with the interface configuration window (the said window will have to be renamed). Would you be up for that change? Seems fairly straightforward.

**Comment by SyrianSpock** [comment]
Sure, how should we name it?

**Comment by pavel-kirienko** [comment]
"Setup" should work I suppose.

**Comment by SyrianSpock** [comment]
Done.

**Comment by pavel-kirienko** [comment]
Sorry, what I meant is that the custom DSDL load paths should be configured on the same window as the interfaces. The objective is to simplify the startup process - we're going to show only one window, where both the interface and the custom DSDL can be configured, rather than two separate windows. Could you please add your widgets to the existing interface selection window, and then rename it as we discussed above? Thanks!

**Comment by SyrianSpock** [comment]
Oh I see, sure I'll do it.

**Comment by SyrianSpock** [comment]
Done, looks like this now. 
screenshot from 2018-02-16 15 50 28

**Comment by pavel-kirienko** [comment]
:+1:

**Pull request merged**
